language: python
python:
  - '3.6'

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: deploy
      deploy:
        provider: pypi
        username: '__token__'
        password: 
          secret: $PYPI_TOKEN
        on:
          tags: true
          branch: master

stages:
  - deploy