language: python
python:
- '3.6'
install:
- pip install -q -r requirements.txt .
- pip install coverage
notifications:
  email: false
deploy:
  provider: pypi
  user: stoick01
  password:
    secure: lSOlMSj4k9I6AO4TeD13iFDEUy/wz5alG/vlb9VyJY5DwJN5afXuAipgyS02Rln+c8unjkOFg9YnzlRIIxJvUYOPjTlocw8D2amLt9miw4Fttf0lsL6s5grB2sZ3FQCbuH4mrmDLHqK5HYHrE9QzhkUqxjl1vW/fzWoRvqQBfb2bkYVofmPmftiUbqlVjYK/Ycxi/UEqFrGrmVuXVVVLxogSiYSR+/LFQx1PhbVcuA/Nx3bvRAtdA+ZMqpZSRDl4O/5UCrhMO/lp9pA4HA8J1XBARtc3PtBscP2KhYpK5cHr9mG2pgY+yJrWDiMvHZAhUcd+650hg2OiTAsV6xCO12ONvpesPmK/B5I57jnpXsDspOHXQbv0Sc6zQmPS8FqNgyXhkYkZrnBSyw5Jde3qAMO47k9MnCUqcx/HQSzS8y5NoVRcLX3Wg9DrNYz+1w3ZY7PHRgqiarqG9P7D9RyLOJz28vXu0VwbrpKumD/9d76mznhRLR1JeRtZ48AD9hnZ9aem/zgatrA7/L6p6l/eHU73MxKFbEJ1B36I1F/dtF7kLrPHBSrcLszxcl481edLDddWZjWYyR1/NOxgnzsvEQBM233EoecFSLzCov5hdc1SPTEFr3RuxlnZBYgftH0Qmjy90cweOqEQkm7WNRJ0BZwPo5v0SImCfbYiuUGGoRQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Stoick01/bluebird
  skip_cleanup: 'true'
