language: python
deploy:
  provider: pypi
  username: __token__
  server: https://upload.pypi.org/legacy/
  distributions: sdist bdist_wheel
  on:
    branch: master
  password:
    secure: F2Ps6TXikQxJCI5A63zjPPr0wv2+2wiLTEVOkQNSelOnsujEK98LSIusOaFWDhwqfusivPByzuRt8POSLkcI5Nr29t/axjBAMTj7yevazqw1Eo0wtCu5RLt4ejJdJ3HCWI9RENZvG2SVvBraoZHVRVt3SeNmnknUTpkmpmdiWWewvxR97/7f1FoBuwFFUIUvbasaupIokLNAKi9F8sG8ObS8NVxELOo3skUTn/E7lBS2VRa6+UZfXZ/te6esViBXPPyPG1d+/smVeZZOKx3PaY9Ew0HlUHCzeXBrwmdV19YRe2E3LoZEyoQeKoQ8YZHEPCOAfCPc3yPeoGHf/AdRLiVtn7l2Iw7d/x3X0iDTaZ7N0BHQyaWGSonXEZuk9s9xNm8fP1/KEp18+qPjgs4J4wyzL4Fqq4bbKq7bnA7zMKBAdTLC2kvmxPXUypk/pEm22RE2pERIv0oBqB/AHSiS6YruYJzcnj8YQP3KDQCqwkV1DJxZSXJGMpdOyqU2Q8xmxW8/D2B/3OOzBUzOkJMWef+VSb74s4YxyVccjhjj+q/WPeQFNigWexPPWEYcxXghqaCqZqC9holJXZafwNJ/T0npN3hKIIyHS1JvAIKeey8DmnwnkKyGS/uoMbCSujarKFargqxqLSuIaNZGPYoKDXkKdX27GrNKFsGZ2b0zn3s=
