deploy:
  provider: pypi
  username: __token__
  server: https://upload.pypi.org/legacy/
  password: $PIPY_TOKEN
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.6"