language: python
deploy:
  provider: pypi
  username: "__token__"
  server: https://upload.pypi.org/legacy/
  password: 
    secure: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.6"


sudo: required

services:
  - docker

language: python
python:
  - '3.6'

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: deploy
      deploy:
        provider: pypi
        username: '__token__'
        password: $PYPI_TOKEN
        on:
          branch: master

stages:
  - deploy