language: python
deploy:
  provider: pypi
  username: stoick01
  password: 
    secure: $PIPY_TOKEN
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.6"